"""
AlgoDAO — Deployment Script
Deploys the DAO governance contract to Algorand Testnet using AlgoKit

Usage:
    python scripts/deploy.py --network testnet

Prerequisites:
    1. Run create_token.py first to get governance_token_id
    2. Set DEPLOYER_MNEMONIC env variable
    3. Fund your testnet account: https://dispenser.testnet.aws.algodev.network/
"""

import argparse
import json
import os
import sys
from pathlib import Path

from algokit_utils import AlgoAmount, AlgorandClient
from algosdk import mnemonic


def deploy(network: str = "testnet") -> dict:
    print(f"\n🏛  AlgoDAO — Deploying to Algorand {network.upper()}")
    print("=" * 55)

    # Connect to network
    if network == "localnet":
        algorand = AlgorandClient.default_local_net()
        deployer = algorand.account.kmd.get_or_create_wallet_account(
            "deployer", AlgoAmount.from_algos(1000)
        )
    else:
        algorand = AlgorandClient.testnet()
        mnemonic_phrase = os.environ.get("DEPLOYER_MNEMONIC")
        if not mnemonic_phrase:
            print("❌ DEPLOYER_MNEMONIC not set!")
            print("   Export your 25-word mnemonic:")
            print('   export DEPLOYER_MNEMONIC="word1 word2 ... word25"')
            print("   Fund testnet: https://dispenser.testnet.aws.algodev.network/")
            sys.exit(1)
        private_key = mnemonic.to_private_key(mnemonic_phrase)
        deployer = algorand.account.from_private_key(private_key)

    balance = algorand.account.get_information(deployer.address)
    print(f"📍 Deployer:  {deployer.address}")
    print(f"💰 Balance:   {balance['amount'] / 1_000_000:.4f} ALGO")

    if balance["amount"] < 2_000_000:
        print("⚠️  Low balance! Fund your account:")
        print("   https://dispenser.testnet.aws.algodev.network/")
        sys.exit(1)

    # Load governance token ID
    token_file = Path("governance_token.json")
    if token_file.exists():
        with open(token_file) as f:
            token_info = json.load(f)
        governance_token_id = token_info["asset_id"]
        print(f"🪙  Governance Token ASA ID: {governance_token_id}")
    else:
        print("⚠️  governance_token.json not found.")
        print("   Run: python scripts/create_token.py --network testnet")
        print("   Using token ID 0 (demo mode — replace in production)")
        governance_token_id = 0

    # Import contract client (generated by: algokit compile)
    try:
        from smart_contracts.algodao import AlgoDAO
    except ImportError:
        print("❌ Run 'algokit compile smart_contracts/algodao.py' first")
        sys.exit(1)

    # Deploy the DAO contract
    print("\n📦 Deploying AlgoDAO smart contract...")
    client = algorand.client.get_typed_app_client(
        AlgoDAO,
        creator=deployer,
        default_sender=deployer.address,
        default_signer=deployer.signer,
    )

    client.create_dao(
        dao_name="AlgoDAO Community",
        dao_description="Decentralized governance for the Algorand community. Vote on proposals, manage treasury, shape the protocol.",
        governance_token_id=governance_token_id,
        min_tokens_to_propose=100,          # 100 ADAO tokens to propose
        voting_period_seconds=604_800,      # 7 days default voting window
        quorum_percentage=10,               # 10% of supply must vote
    )

    app_id = client.app_id
    app_address = client.app_address

    # Fund contract with initial treasury
    print("💸 Funding DAO treasury (0.5 ALGO initial)...")
    algorand.send.payment(
        sender=deployer.address,
        receiver=app_address,
        amount=AlgoAmount.from_algos(0.5),
        signer=deployer.signer,
        note=b"AlgoDAO initial treasury funding",
    )

    deployment_info = {
        "network": network,
        "app_id": app_id,
        "app_address": app_address,
        "governance_token_id": governance_token_id,
        "deployer": deployer.address,
        "explorer_url": f"https://testnet.explorer.perawallet.app/application/{app_id}",
        "algoexplorer_url": f"https://testnet.algoexplorer.io/application/{app_id}",
    }

    print("\n" + "=" * 55)
    print("✅ ALGODAO DEPLOYMENT SUCCESSFUL!")
    print("=" * 55)
    print(f"📋 App ID:        {app_id}")
    print(f"📫 App Address:   {app_address}")
    print(f"🪙  Gov Token ID: {governance_token_id}")
    print(f"🔍 Pera Explorer: {deployment_info['explorer_url']}")
    print("=" * 55)
    print(f"\n⚠️  Add to frontend/.env.local:")
    print(f"   VITE_APP_ID={app_id}")
    print(f"   VITE_GOVERNANCE_TOKEN_ID={governance_token_id}")

    with open("deployment.json", "w") as f:
        json.dump(deployment_info, f, indent=2)
    print(f"\n💾 Deployment info saved to deployment.json")
    return deployment_info


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Deploy AlgoDAO to Algorand")
    parser.add_argument("--network", choices=["localnet", "testnet"], default="testnet")
    args = parser.parse_args()
    deploy(args.network)
